# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: install dependencies
      - run:
          name: install dependencies and chromedriver
          command: |
            sudo apt-get install -yqq unzip curl
            wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
            chmod +x /usr/local/bin/chromedriver
            unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
            pip install -r requirements.txt
      # Step 3: run application
      - run: 
          name: run application
          command: |
            python app.py
          background: true
      - run:
          name: run tests
          command: |
            pytest -v 
